<a href="https://colab.research.google.com/github/ZsirosB/PytorchTutorial/blob/main/Tensor.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
my_list = [[1,2,3,4,5],[6,7,8,9,10]]
my_list

[[1, 2, 3, 4, 5], [6, 7, 8, 9, 10]]

In [3]:
import torch
import numpy as np
np1 = np.random.rand(3,4)
np1

array([[0.32102169, 0.31324707, 0.25326863, 0.57569409],
       [0.62938852, 0.93122054, 0.8305156 , 0.60607031],
       [0.2277438 , 0.78209467, 0.43286081, 0.89239313]])

In [4]:
np1.dtype

dtype('float64')

In [5]:
tensor_2d = torch.randn(3,4)
tensor_2d

tensor([[ 0.8524, -2.4949,  0.0337,  1.5323],
        [ 0.7387,  0.7368,  0.0777, -0.7238],
        [-0.9937, -0.6993,  0.4653,  1.2757]])

In [6]:
tensor_3d = torch.zeros(2,3,4)
tensor_3d

tensor([[[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]],

        [[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]]])